### ISSUE TITLE
Implement admin translation endpoint

### ISSUE THREAD

**Issue by frzifus** [quixsi/lets-party#58]
Translation fields are provided on the admin page. However, there is currently no handler to update them.

![image](https://github.com/frzifus/lets-party/assets/10403402/e74ca641-e3f9-4742-b586-dc31e005d859)

The handler should be registered in the admin area:
https://github.com/frzifus/lets-party/blob/e1bd39457362a4c6b3e6d397a656bf51483a7849/intern/server/server.go#L94-L101

And implemented similar to the submit method:
https://github.com/frzifus/lets-party/blob/e1bd39457362a4c6b3e6d397a656bf51483a7849/intern/server/templates/handler.go#L255-L315

**Comment by KnutZuidema** [comment]
@frzifus I'll pick this up
